// Auto-generated from frontend src/data/sarees.ts

const sareeImages = [
  "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1593030103066-0093718efeb9?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1602214099785-3dd7e52f7f70?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1614886137799-f9b5d5a17db9?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1631886742625-82534f2c5ca8?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1553531384-cc64ac80f931?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1610561977921-99dc5c68d857?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600&h=800&fit=crop",
  "https://images.unsplash.com/photo-1622282220395-4b9a6ab2a7de?w=600&h=800&fit=crop",
];

const getImage = (i) => sareeImages[i % sareeImages.length];

const artisans = [
  {
    id: "a1",
    name: "Ramaiah Devaraju",
    village: "Arsikere",
    district: "Hassan",
    experience: 35,
    specialization: "Gold Zari Weaving",
    phone: "+91 98456 12301",
    email: "ramaiah.devaraju@mysoremagga.in",
    whatsapp: "919845612301",
    bio: "Third-generation master weaver specializing in traditional gold zari patterns. His sarees have been worn at royal ceremonies.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop",
    rating: 4.9,
    totalSarees: 312,
  },
  {
    id: "a2",
    name: "Lakshmi Narayana",
    village: "T. Narasipura",
    district: "Mysore",
    experience: 28,
    specialization: "Temple Border Designs",
    phone: "+91 98456 12302",
    email: "lakshmi.narayana@mysoremagga.in",
    whatsapp: "919845612302",
    bio: "Expert in intricate temple border patterns inspired by Hoysala sculptures. Her work is collected internationally.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
    rating: 4.8,
    totalSarees: 247,
  },
  {
    id: "a3",
    name: "Venkatesh Shastri",
    village: "Hunsur",
    district: "Mysore",
    experience: 42,
    specialization: "Bridal Silk",
    phone: "+91 98456 12303",
    email: "venkatesh.shastri@mysoremagga.in",
    whatsapp: "919845612303",
    bio: "Legendary bridal silk weaver with 42 years of expertise. His bridal sarees are considered heirlooms in Kodagu.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    rating: 5.0,
    totalSarees: 485,
  },
  {
    id: "a4",
    name: "Savitha Gowda",
    village: "Maddur",
    district: "Mandya",
    experience: 22,
    specialization: "Soft Silk",
    phone: "+91 98456 12304",
    email: "savitha.gowda@mysoremagga.in",
    whatsapp: "919845612304",
    bio: "Young master weaver known for breathable soft silk in pastel tones. She blends tradition with modern palettes.",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=400&fit=crop",
    rating: 4.7,
    totalSarees: 189,
  },
  {
    id: "a5",
    name: "Krishnamurthy Iyengar",
    village: "Srirangapatna",
    district: "Mandya",
    experience: 38,
    specialization: "Royal Checks & Stripes",
    phone: "+91 98456 12305",
    email: "krishna.iyengar@mysoremagga.in",
    whatsapp: "919845612305",
    bio: "Master of geometric patterns and royal checks. His looms produce sarees fit for Karnataka's cultural ambassadors.",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    rating: 4.9,
    totalSarees: 356,
  },
  {
    id: "a6",
    name: "Annapoorna Devi",
    village: "Mandya",
    district: "Mandya",
    experience: 30,
    specialization: "Designer Silk",
    phone: "+91 98456 12306",
    email: "annapoorna.devi@mysoremagga.in",
    whatsapp: "919845612306",
    bio: "Pioneer of designer silk fusion blending Mysore traditions with contemporary art motifs. Her work exhibited in Delhi and London.",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop",
    rating: 4.8,
    totalSarees: 203,
  },
];

const categories = [
  "All",
  "Traditional Mysore Silk",
  "Bridal Silk",
  "Soft Silk",
  "Temple Border Silk",
  "Premium Gold Zari Silk",
  "Designer Collection",
];

const sarees = [
  // Traditional Mysore Silk (1-18)
  {
    id: "s1", name: "Royal Mysore Crimson", price: 12500, originalPrice: 15000,
    category: "Traditional Mysore Silk", color: "Crimson Red", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Classic Mysore silk in rich crimson with traditional gold zari border. Hand-woven on pit loom over 12 days.",
    inStock: true, stockCount: 8, image: getImage(0), badge: "Bestseller",
    weight: "450g", zariType: "Pure Gold Zari", occasion: "Weddings, Festivals",
    careInstructions: "Dry clean only",
  },
  {
    id: "s2", name: "Palace Gold Cream", price: 14800, originalPrice: 18000,
    category: "Traditional Mysore Silk", color: "Ivory Cream", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Exquisite ivory silk adorned with palace-inspired gold zari motifs. A timeless piece for special occasions.",
    inStock: true, stockCount: 5, image: getImage(1), badge: "Heritage Pick",
    weight: "480g", zariType: "Pure Gold Zari", occasion: "Weddings, Receptions",
    careInstructions: "Dry clean only",
  },
  {
    id: "s3", name: "Mysore Blue Royale", price: 11200,
    category: "Traditional Mysore Silk", color: "Royal Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Deep royal blue Mysore silk with classic gold checks and traditional border. Woven with 100% pure gold zari.",
    inStock: true, stockCount: 12, image: getImage(2),
    weight: "440g", zariType: "Pure Gold Zari", occasion: "Festivals, Cultural Events",
  },
  {
    id: "s4", name: "Forest Green Heritage", price: 13600,
    category: "Traditional Mysore Silk", color: "Emerald Green", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Lush forest green Mysore silk with intricate gold zari weaving. The color is achieved through organic silk dyeing.",
    inStock: true, stockCount: 6, image: getImage(3),
    weight: "460g", zariType: "Pure Gold Zari", occasion: "Weddings, Pooja",
  },
  {
    id: "s5", name: "Sunset Turmeric Silk", price: 10800,
    category: "Traditional Mysore Silk", color: "Golden Yellow", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Vibrant turmeric-yellow Mysore silk with traditional sun motif zari border. Perfect for auspicious occasions.",
    inStock: true, stockCount: 9, image: getImage(4),
    weight: "430g", zariType: "Gold Zari", occasion: "Festivals, Pujas",
  },
  {
    id: "s6", name: "Deep Maroon Classic", price: 15200,
    category: "Traditional Mysore Silk", color: "Deep Maroon", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Rich maroon Mysore silk, a quintessential Karnataka heirloom. Wide gold zari border with elephant motifs.",
    inStock: true, stockCount: 4, image: getImage(5), badge: "Classic",
    weight: "470g", zariType: "Pure Gold Zari", occasion: "All Occasions",
  },
  {
    id: "s7", name: "Peacock Blue Traditional", price: 12800,
    category: "Traditional Mysore Silk", color: "Peacock Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Stunning peacock blue silk with intricate peacock feather gold zari motifs throughout the pallu.",
    inStock: true, stockCount: 7, image: getImage(6),
    weight: "455g", zariType: "Pure Gold Zari", occasion: "Weddings, Cultural Events",
  },
  {
    id: "s8", name: "Sandal Wood Classic", price: 11500,
    category: "Traditional Mysore Silk", color: "Sandalwood", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Warm sandalwood Mysore silk with delicate gold zari checks and traditional double border.",
    inStock: true, stockCount: 11, image: getImage(7),
    weight: "445g", zariType: "Gold Zari", occasion: "Casual, Festivals",
  },
  {
    id: "s9", name: "Amethyst Purple Heritage", price: 13200,
    category: "Traditional Mysore Silk", color: "Royal Purple", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Majestic purple Mysore silk with gold zari running border and traditional pallu with floral motifs.",
    inStock: false, stockCount: 0, image: getImage(8),
    weight: "460g", zariType: "Pure Gold Zari", occasion: "Weddings, Receptions",
  },
  {
    id: "s10", name: "Brick Red Handloom", price: 9800,
    category: "Traditional Mysore Silk", color: "Brick Red", fabric: "Pure Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Traditional brick red Mysore silk hand-woven with antique zari. An everyday luxury at an accessible price.",
    inStock: true, stockCount: 15, image: getImage(9),
    weight: "420g", zariType: "Antique Zari", occasion: "Festivals, Casual Occasions",
  },
  {
    id: "s11", name: "Champagne Gold Silk", price: 16500, originalPrice: 20000,
    category: "Traditional Mysore Silk", color: "Champagne Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Lustrous champagne silk that gleams under light. Heavy gold zari work with Hampi ruins motif.",
    inStock: true, stockCount: 3, image: getImage(10), badge: "Limited",
    weight: "490g", zariType: "Pure Gold Zari", occasion: "Premium Weddings",
  },
  {
    id: "s12", name: "Teal Ocean Mysore", price: 11900,
    category: "Traditional Mysore Silk", color: "Teal", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Deep teal Mysore silk with traditional gold zari border inspired by Cauvery river patterns.",
    inStock: true, stockCount: 8, image: getImage(11),
    weight: "450g", zariType: "Gold Zari", occasion: "Festivals, Casual",
  },
  {
    id: "s13", name: "Classic Black Mysore", price: 14200,
    category: "Traditional Mysore Silk", color: "Midnight Black", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Rare black Mysore silk with wide pure gold zari border. A collector's piece with dramatic contrast.",
    inStock: true, stockCount: 5, image: getImage(12),
    weight: "465g", zariType: "Pure Gold Zari", occasion: "Formal Events",
  },
  {
    id: "s14", name: "Rose Pink Mysore", price: 10500,
    category: "Traditional Mysore Silk", color: "Rose Pink", fabric: "Pure Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Soft rose pink Mysore silk with delicate floral gold zari motifs. Woven by young master artisan.",
    inStock: true, stockCount: 10, image: getImage(13),
    weight: "435g", zariType: "Gold Zari", occasion: "Casual, Festivals",
  },
  {
    id: "s15", name: "Navy Blue Royale Silk", price: 13800,
    category: "Traditional Mysore Silk", color: "Navy Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Deep navy silk with golden temple border and intricate pallu. A statement piece for important occasions.",
    inStock: true, stockCount: 6, image: getImage(14),
    weight: "455g", zariType: "Pure Gold Zari", occasion: "Weddings, Cultural Events",
  },
  {
    id: "s16", name: "Burnt Orange Heritage", price: 12100,
    category: "Traditional Mysore Silk", color: "Burnt Orange", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Vibrant burnt orange silk with silver-gold mixed zari border. A contemporary traditional piece.",
    inStock: true, stockCount: 7, image: getImage(0),
    weight: "445g", zariType: "Mixed Zari", occasion: "Weddings, Festivals",
  },
  {
    id: "s17", name: "Mango Yellow Traditional", price: 9500,
    category: "Traditional Mysore Silk", color: "Mango Yellow", fabric: "Pure Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Bright mango yellow silk - the color of Karnataka summer. Simple gold border with intricate pallu.",
    inStock: true, stockCount: 13, image: getImage(1),
    weight: "425g", zariType: "Gold Zari", occasion: "Festivals, Casual",
  },
  {
    id: "s18", name: "Olive Green Weave", price: 11300,
    category: "Traditional Mysore Silk", color: "Olive Green", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Earthy olive green Mysore silk with organic feel. Natural dye with traditional gold border.",
    inStock: true, stockCount: 9, image: getImage(2),
    weight: "440g", zariType: "Gold Zari", occasion: "Casual, Festivals",
  },

  // Bridal Silk (19-34)
  {
    id: "s19", name: "Grand Bridal Kanchipuram Fusion", price: 45000, originalPrice: 55000,
    category: "Bridal Silk", color: "Ruby Red & Gold", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Ultimate bridal saree fusing Mysore and Kanchipuram traditions. 22-day weaving, pure gold zari throughout.",
    inStock: true, stockCount: 2, image: getImage(3), badge: "Bridal Exclusive",
    weight: "780g", zariType: "Pure 22K Gold Zari", occasion: "Weddings Only",
    careInstructions: "Professional dry clean only",
  },
  {
    id: "s20", name: "Royal Maroon Bridal", price: 38000, originalPrice: 45000,
    category: "Bridal Silk", color: "Royal Maroon", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Deep maroon bridal silk with intricate gold zari swan and peacock pallu. Bride's eternal choice.",
    inStock: true, stockCount: 3, image: getImage(4), badge: "Top Bridal",
    weight: "720g", zariType: "Pure Gold Zari", occasion: "Weddings",
  },
  {
    id: "s21", name: "Golden Bridal Silk", price: 52000,
    category: "Bridal Silk", color: "Pure Gold", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Legendary golden bridal silk. Entire saree woven in gold tones with heavy 22K zari work. Museum quality.",
    inStock: true, stockCount: 1, image: getImage(5), badge: "Masterpiece",
    weight: "820g", zariType: "22K Gold Zari", occasion: "Grand Weddings",
  },
  {
    id: "s22", name: "Ivory Bridal Dream", price: 42000, originalPrice: 50000,
    category: "Bridal Silk", color: "Ivory White", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Pristine ivory bridal silk for modern brides. Subtle gold zari with lotus and vine motifs.",
    inStock: true, stockCount: 4, image: getImage(6),
    weight: "700g", zariType: "Pure Gold Zari", occasion: "Weddings, Engagement",
  },
  {
    id: "s23", name: "Peacock Green Bridal", price: 47000,
    category: "Bridal Silk", color: "Peacock Green & Gold", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Peacock-inspired bridal masterpiece. The entire pallu depicts a peacock in full bloom using gold zari.",
    inStock: true, stockCount: 2, image: getImage(7), badge: "Artisan Special",
    weight: "760g", zariType: "Pure Gold Zari", occasion: "Weddings",
  },
  {
    id: "s24", name: "Bridal Rose & Gold", price: 35000,
    category: "Bridal Silk", color: "Rose & Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Contemporary bridal choice in rose silk with modern geometric gold zari. For the modern traditional bride.",
    inStock: true, stockCount: 5, image: getImage(8),
    weight: "680g", zariType: "Gold Zari", occasion: "Weddings, Reception",
  },
  {
    id: "s25", name: "Deep Blue Bridal Classic", price: 40000, originalPrice: 48000,
    category: "Bridal Silk", color: "Midnight Blue", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Midnight blue bridal silk with silver and gold combined zari. For the bride who wants to stand out.",
    inStock: false, stockCount: 0, image: getImage(9),
    weight: "710g", zariType: "Silver-Gold Zari", occasion: "Evening Weddings",
  },
  {
    id: "s26", name: "Crimson Bridal Zari", price: 36000,
    category: "Bridal Silk", color: "Bright Crimson", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Vibrant crimson bridal silk with heavy zari work. Traditional choice with modern crafting.",
    inStock: true, stockCount: 6, image: getImage(10),
    weight: "690g", zariType: "Pure Gold Zari", occasion: "Weddings",
  },
  {
    id: "s27", name: "Green Bridal Heritage", price: 43000,
    category: "Bridal Silk", color: "Emerald Green", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Auspicious green bridal silk representing prosperity. Wide gold zari border with kalash motifs.",
    inStock: true, stockCount: 3, image: getImage(11),
    weight: "730g", zariType: "Pure Gold Zari", occasion: "Weddings",
  },
  {
    id: "s28", name: "Orange Silk Bridal", price: 32000,
    category: "Bridal Silk", color: "Bright Orange", fabric: "Pure Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Bright orange bridal silk - the color of turmeric and auspiciousness. Simple yet striking gold border.",
    inStock: true, stockCount: 7, image: getImage(12),
    weight: "665g", zariType: "Gold Zari", occasion: "Weddings, Mehendi",
  },
  {
    id: "s29", name: "Purple Grand Bridal", price: 48000, originalPrice: 58000,
    category: "Bridal Silk", color: "Royal Purple", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Grand purple bridal silk with elaborate peacock and floral gold zari throughout. A 25-day weaving masterwork.",
    inStock: true, stockCount: 1, image: getImage(13), badge: "Grand Masterpiece",
    weight: "800g", zariType: "22K Gold Zari", occasion: "Grand Weddings",
  },
  {
    id: "s30", name: "Champagne Bridal Silk", price: 39000,
    category: "Bridal Silk", color: "Champagne", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Understated champagne bridal silk for the minimalist bride. Clean gold border with floral motifs.",
    inStock: true, stockCount: 4, image: getImage(14),
    weight: "680g", zariType: "Gold Zari", occasion: "Destination Weddings",
  },
  {
    id: "s31", name: "Teal Bridal Grandeur", price: 44000,
    category: "Bridal Silk", color: "Teal & Gold", fabric: "Pure Mulberry Silk - Heavy",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Striking teal bridal silk with elaborate gold zari depicting the Mysore Dasara procession.",
    inStock: true, stockCount: 2, image: getImage(0),
    weight: "740g", zariType: "Pure Gold Zari", occasion: "Premium Weddings",
  },
  {
    id: "s32", name: "Tangerine Bridal Silk", price: 34000,
    category: "Bridal Silk", color: "Tangerine", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Fresh tangerine bridal silk with contemporary zari patterns. Perfect for day weddings.",
    inStock: true, stockCount: 5, image: getImage(1),
    weight: "670g", zariType: "Gold Zari", occasion: "Day Weddings",
  },
  {
    id: "s33", name: "Magenta Bridal Silk", price: 37000,
    category: "Bridal Silk", color: "Magenta", fabric: "Pure Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Bold magenta bridal silk for the vivacious bride. Heavy pallu with floral and vine gold zari.",
    inStock: true, stockCount: 6, image: getImage(2),
    weight: "695g", zariType: "Gold Zari", occasion: "Weddings, Reception",
  },
  {
    id: "s34", name: "Silver Thread Bridal", price: 46000,
    category: "Bridal Silk", color: "Silver & White", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Rare silver zari bridal silk in pristine white. For the unconventional bride seeking ethereal elegance.",
    inStock: true, stockCount: 2, image: getImage(3), badge: "Rare Piece",
    weight: "720g", zariType: "Pure Silver Zari", occasion: "Weddings",
  },

  // Soft Silk (35-50)
  {
    id: "s35", name: "Blush Soft Silk", price: 7800,
    category: "Soft Silk", color: "Blush Pink", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Feather-light blush pink soft silk. Perfect for office wear and casual occasions. Breathable and comfortable.",
    inStock: true, stockCount: 18, image: getImage(4), badge: "Lightweight",
    weight: "280g", zariType: "Light Gold Zari", occasion: "Office, Casual",
  },
  {
    id: "s36", name: "Sky Blue Soft Silk", price: 6900,
    category: "Soft Silk", color: "Sky Blue", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Light as air sky blue soft silk. Minimal zari border for an understated elegant look.",
    inStock: true, stockCount: 20, image: getImage(5),
    weight: "260g", zariType: "Minimal Zari", occasion: "Daily Wear, Office",
  },
  {
    id: "s37", name: "Mint Green Soft Silk", price: 7200,
    category: "Soft Silk", color: "Mint Green", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Cool mint green soft silk ideal for summer occasions. Thin border with delicate embroidery.",
    inStock: true, stockCount: 15, image: getImage(6),
    weight: "270g", zariType: "Silver Zari", occasion: "Summer Events, Casual",
  },
  {
    id: "s38", name: "Lavender Soft Silk", price: 7500,
    category: "Soft Silk", color: "Lavender", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Dreamy lavender soft silk with floral motifs. A millennial favorite for weddings and parties.",
    inStock: true, stockCount: 14, image: getImage(7),
    weight: "275g", zariType: "Light Zari", occasion: "Parties, Weddings",
  },
  {
    id: "s39", name: "Peach Soft Silk", price: 6700,
    category: "Soft Silk", color: "Peach", fabric: "Soft Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Warm peach soft silk with minimal gold border. Everyday luxury that drapes beautifully.",
    inStock: true, stockCount: 22, image: getImage(8),
    weight: "265g", zariType: "Gold Zari", occasion: "Daily Wear",
  },
  {
    id: "s40", name: "Aqua Teal Soft Silk", price: 7300,
    category: "Soft Silk", color: "Aqua Teal", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Refreshing aqua teal soft silk. Contemporary color with traditional weave. Very popular among young buyers.",
    inStock: true, stockCount: 17, image: getImage(9),
    weight: "272g", zariType: "Silver Zari", occasion: "Parties, Casual",
  },
  {
    id: "s41", name: "Butter Yellow Soft Silk", price: 6500,
    category: "Soft Silk", color: "Butter Yellow", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Warm butter yellow soft silk with a gentle gold border. Perfect for summer days.",
    inStock: true, stockCount: 19, image: getImage(10),
    weight: "260g", zariType: "Light Gold Zari", occasion: "Summer, Casual",
  },
  {
    id: "s42", name: "Off-White Soft Silk", price: 7100,
    category: "Soft Silk", color: "Off White", fabric: "Soft Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Pristine off-white soft silk with delicate gold thread running border. Elegant simplicity.",
    inStock: true, stockCount: 12, image: getImage(11),
    weight: "268g", zariType: "Light Gold Thread", occasion: "Office, Casual",
  },
  {
    id: "s43", name: "Coral Pink Soft Silk", price: 7600,
    category: "Soft Silk", color: "Coral Pink", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Lively coral pink soft silk. Lightweight with beautiful drape and contemporary appeal.",
    inStock: true, stockCount: 16, image: getImage(12),
    weight: "278g", zariType: "Gold Zari", occasion: "Festivals, Parties",
  },
  {
    id: "s44", name: "Turquoise Soft Silk", price: 7400,
    category: "Soft Silk", color: "Turquoise", fabric: "Soft Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Bright turquoise soft silk with silver zari. A young, vibrant look for festive occasions.",
    inStock: true, stockCount: 11, image: getImage(13),
    weight: "273g", zariType: "Silver Zari", occasion: "Festivals, Parties",
  },
  {
    id: "s45", name: "Sage Green Soft Silk", price: 6800,
    category: "Soft Silk", color: "Sage Green", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Organic sage green soft silk. Muted, sophisticated, and perfect for modern working professionals.",
    inStock: true, stockCount: 13, image: getImage(14),
    weight: "264g", zariType: "Minimal Zari", occasion: "Office, Casual",
  },
  {
    id: "s46", name: "Dusty Rose Soft Silk", price: 7200,
    category: "Soft Silk", color: "Dusty Rose", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Muted dusty rose soft silk with delicate border. Romantic and refined for any occasion.",
    inStock: true, stockCount: 14, image: getImage(0),
    weight: "270g", zariType: "Light Gold Zari", occasion: "Casual, Parties",
  },
  {
    id: "s47", name: "Slate Blue Soft Silk", price: 7000,
    category: "Soft Silk", color: "Slate Blue", fabric: "Soft Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Sophisticated slate blue soft silk with geometric minimal zari. Perfect for formal occasions.",
    inStock: true, stockCount: 10, image: getImage(1),
    weight: "267g", zariType: "Silver Zari", occasion: "Formal, Office",
  },
  {
    id: "s48", name: "Warm Grey Soft Silk", price: 6600,
    category: "Soft Silk", color: "Warm Grey", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Contemporary warm grey soft silk — an unconventional choice for the fashion-forward woman.",
    inStock: true, stockCount: 9, image: getImage(2),
    weight: "261g", zariType: "Gold Zari", occasion: "Formal, Office",
  },
  {
    id: "s49", name: "Lilac Soft Silk", price: 7300,
    category: "Soft Silk", color: "Lilac", fabric: "Soft Mulberry Silk",
    artisanId: "a4", artisanName: "Savitha Gowda", location: "Maddur, Mandya",
    description: "Delicate lilac soft silk with feather-light drape. Ideal for spring and summer celebrations.",
    inStock: true, stockCount: 15, image: getImage(3),
    weight: "271g", zariType: "Light Zari", occasion: "Casual, Festivals",
  },
  {
    id: "s50", name: "Ivory Soft Silk", price: 7500,
    category: "Soft Silk", color: "Ivory", fabric: "Soft Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Pure ivory soft silk with minimal gold thread. Timeless, elegant, and wearable for any event.",
    inStock: true, stockCount: 16, image: getImage(4),
    weight: "269g", zariType: "Minimal Gold Thread", occasion: "All Occasions",
  },

  // Temple Border Silk (51-64)
  {
    id: "s51", name: "Temple Red Gold Border", price: 18500, originalPrice: 22000,
    category: "Temple Border Silk", color: "Vermillion Red", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Exquisite temple border silk with Hoysala-inspired motifs. The border alone takes 5 days to weave.",
    inStock: true, stockCount: 5, image: getImage(5), badge: "Artisan Pride",
    weight: "520g", zariType: "Pure Gold Zari", occasion: "Temple Visits, Festivals",
  },
  {
    id: "s52", name: "Temple Cream Heritage", price: 19200,
    category: "Temple Border Silk", color: "Cream", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Cream silk with elaborate Belur temple motif border. Each motif depicts a Hoysala sculpture.",
    inStock: true, stockCount: 4, image: getImage(6), badge: "Heritage Craft",
    weight: "530g", zariType: "Pure Gold Zari", occasion: "Temple, Festivals",
  },
  {
    id: "s53", name: "Temple Green Gold", price: 17800,
    category: "Temple Border Silk", color: "Dark Green", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Dark green temple silk with intricate naga (serpent) border motifs. Sacred and beautiful.",
    inStock: true, stockCount: 6, image: getImage(7),
    weight: "515g", zariType: "Pure Gold Zari", occasion: "Temple, Festivals",
  },
  {
    id: "s54", name: "Temple Blue Mysore", price: 20000,
    category: "Temple Border Silk", color: "Peacock Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Peacock blue with the famous Chamundeshwari temple border. A divine piece of Karnataka heritage.",
    inStock: false, stockCount: 0, image: getImage(8), badge: "Divine Collection",
    weight: "535g", zariType: "Pure Gold Zari", occasion: "Religious Events",
  },
  {
    id: "s55", name: "Temple Maroon Grandeur", price: 21000, originalPrice: 25000,
    category: "Temple Border Silk", color: "Deep Maroon", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Maroon silk with the iconic Mysore Palace gate motif in the border. Royal and sacred.",
    inStock: true, stockCount: 3, image: getImage(9), badge: "Royal Sacred",
    weight: "540g", zariType: "22K Gold Zari", occasion: "Weddings, Festivals",
  },
  {
    id: "s56", name: "Temple Purple Silk", price: 18900,
    category: "Temple Border Silk", color: "Royal Purple", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Purple silk with elaborate Srirangapatna temple-inspired border. Historic and majestic.",
    inStock: true, stockCount: 5, image: getImage(10),
    weight: "525g", zariType: "Pure Gold Zari", occasion: "Festivals, Weddings",
  },
  {
    id: "s57", name: "Temple Gold Border Yellow", price: 17500,
    category: "Temple Border Silk", color: "Turmeric Yellow", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Auspicious yellow with pure gold temple border. Worn by women during Dasara celebrations.",
    inStock: true, stockCount: 7, image: getImage(11),
    weight: "510g", zariType: "Pure Gold Zari", occasion: "Dasara, Festivals",
  },
  {
    id: "s58", name: "Temple Ivory Classic", price: 19500,
    category: "Temple Border Silk", color: "Ivory", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Pure ivory with double gold temple border featuring lotus and kalash motifs.",
    inStock: true, stockCount: 4, image: getImage(12),
    weight: "528g", zariType: "Pure Gold Zari", occasion: "Weddings, Festivals",
  },
  {
    id: "s59", name: "Temple Teal Border", price: 17200,
    category: "Temple Border Silk", color: "Deep Teal", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Deep teal with wide temple border depicting the seven hills of Tirumala. Devotional artistry.",
    inStock: true, stockCount: 6, image: getImage(13),
    weight: "515g", zariType: "Gold Zari", occasion: "Religious, Weddings",
  },
  {
    id: "s60", name: "Temple Navy Heritage", price: 20500,
    category: "Temple Border Silk", color: "Navy Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Navy blue with elaborate Vijayanagara empire-inspired temple border. A collector's heritage piece.",
    inStock: true, stockCount: 3, image: getImage(14), badge: "Heritage Collection",
    weight: "538g", zariType: "Pure Gold Zari", occasion: "Festivals, Weddings",
  },
  {
    id: "s61", name: "Temple Orange Mysore", price: 16800,
    category: "Temple Border Silk", color: "Saffron Orange", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Saffron orange - the most sacred color - with pure gold temple border featuring deities.",
    inStock: true, stockCount: 8, image: getImage(0),
    weight: "505g", zariType: "Pure Gold Zari", occasion: "Festivals, Religious",
  },
  {
    id: "s62", name: "Temple Grey Silver", price: 18200,
    category: "Temple Border Silk", color: "Slate Grey", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Unusual grey silk with silver temple border. A modern take on traditional temple weaving.",
    inStock: true, stockCount: 5, image: getImage(1),
    weight: "518g", zariType: "Silver Zari", occasion: "Formal, Festivals",
  },
  {
    id: "s63", name: "Temple Pink Classic", price: 17000,
    category: "Temple Border Silk", color: "Deep Pink", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Deep pink temple silk with Hampi ruins motif border. History woven into every thread.",
    inStock: true, stockCount: 7, image: getImage(2),
    weight: "510g", zariType: "Gold Zari", occasion: "Festivals, Weddings",
  },
  {
    id: "s64", name: "Temple Champagne Royale", price: 22000,
    category: "Temple Border Silk", color: "Champagne", fabric: "Pure Mulberry Silk",
    artisanId: "a2", artisanName: "Lakshmi Narayana", location: "T. Narasipura, Mysore",
    description: "Champagne gold with the grandest temple border featuring Mysore palace gates and elephants.",
    inStock: true, stockCount: 2, image: getImage(3), badge: "Grand Piece",
    weight: "550g", zariType: "22K Pure Gold Zari", occasion: "Premium Events",
  },

  // Premium Gold Zari Silk (65-80)
  {
    id: "s65", name: "24K Gold Weave Mysore", price: 65000, originalPrice: 80000,
    category: "Premium Gold Zari Silk", color: "Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "The pinnacle of Mysore silk. 24K gold wire used in zari. Each piece takes 30 days to weave. Museum-worthy.",
    inStock: true, stockCount: 1, image: getImage(4), badge: "Ultra Premium",
    weight: "950g", zariType: "24K Real Gold Zari", occasion: "Royal Events",
    careInstructions: "Museum-grade preservation required",
  },
  {
    id: "s66", name: "Heavy Gold Zari Crimson", price: 42000,
    category: "Premium Gold Zari Silk", color: "Crimson", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Heavy gold zari crimson silk. The zari weight alone is 200g. Extravagant and breathtaking.",
    inStock: true, stockCount: 3, image: getImage(5), badge: "Heavy Zari",
    weight: "780g", zariType: "Heavy 22K Gold Zari", occasion: "Grand Celebrations",
  },
  {
    id: "s67", name: "Gold Zari Peacock Green", price: 48000,
    category: "Premium Gold Zari Silk", color: "Peacock Green", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Peacock green with heavy gold zari all-over design. The pallu depicts a full peacock in gold wire.",
    inStock: true, stockCount: 2, image: getImage(6), badge: "Zari Masterpiece",
    weight: "830g", zariType: "22K Gold Zari All-over", occasion: "Grand Weddings",
  },
  {
    id: "s68", name: "Gold Zari Royal Blue", price: 44000,
    category: "Premium Gold Zari Silk", color: "Royal Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Royal blue with all-over gold zari checks and elaborate pallu. The Maharaja's court saree.",
    inStock: true, stockCount: 3, image: getImage(7),
    weight: "790g", zariType: "Heavy Gold Zari", occasion: "Royal Events, Weddings",
  },
  {
    id: "s69", name: "Gold Zari Maroon Palace", price: 55000, originalPrice: 68000,
    category: "Premium Gold Zari Silk", color: "Palace Maroon", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "The iconic Palace Maroon with heavy gold zari. This design has been worn at Mysore Dasara for decades.",
    inStock: true, stockCount: 2, image: getImage(8), badge: "Palace Collection",
    weight: "860g", zariType: "22K Pure Gold Zari", occasion: "State Functions, Weddings",
  },
  {
    id: "s70", name: "Gold Zari Ivory Grandeur", price: 58000,
    category: "Premium Gold Zari Silk", color: "Pure Ivory", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Ivory with maximum gold zari density. The body itself is woven with gold zari butti throughout.",
    inStock: true, stockCount: 1, image: getImage(9), badge: "Grandeur",
    weight: "880g", zariType: "24K Gold Zari", occasion: "Premium Weddings",
  },
  {
    id: "s71", name: "Gold Zari Purple", price: 46000,
    category: "Premium Gold Zari Silk", color: "Deep Purple", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Regal purple silk with heavy all-over gold zari. The purple and gold combination is historically royal.",
    inStock: true, stockCount: 4, image: getImage(10),
    weight: "800g", zariType: "Heavy 22K Gold Zari", occasion: "Grand Occasions",
  },
  {
    id: "s72", name: "Gold Zari Champagne", price: 62000,
    category: "Premium Gold Zari Silk", color: "Champagne Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Champagne silk woven almost entirely in gold zari. Nearly indistinguishable from gold fabric itself.",
    inStock: false, stockCount: 0, image: getImage(11), badge: "Sold Out",
    weight: "920g", zariType: "24K Gold Zari", occasion: "Museum, Special Events",
  },
  {
    id: "s73", name: "Gold Zari Dark Green", price: 43000,
    category: "Premium Gold Zari Silk", color: "Bottle Green", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Bottle green with heavy gold zari border and pallu. Traditional and impressive for grand events.",
    inStock: true, stockCount: 3, image: getImage(12),
    weight: "785g", zariType: "22K Gold Zari", occasion: "Weddings, State Functions",
  },
  {
    id: "s74", name: "Gold Zari Teal Masterwork", price: 49000,
    category: "Premium Gold Zari Silk", color: "Deep Teal", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Deep teal with elaborate gold zari all-over weave. A 28-day masterwork of zari craftsmanship.",
    inStock: true, stockCount: 2, image: getImage(13), badge: "28 Days Weave",
    weight: "845g", zariType: "22K Gold Zari All-over", occasion: "Grand Weddings",
  },
  {
    id: "s75", name: "Gold Zari Black Majesty", price: 52000,
    category: "Premium Gold Zari Silk", color: "Midnight Black", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "Rare black silk with maximum gold zari. The dramatic contrast of black and gold is unmatched in luxury.",
    inStock: true, stockCount: 1, image: getImage(14), badge: "Ultra Rare",
    weight: "870g", zariType: "22K Gold Zari", occasion: "Premium Events, Weddings",
  },
  {
    id: "s76", name: "Gold Zari Orange Festival", price: 39000,
    category: "Premium Gold Zari Silk", color: "Saffron Orange", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Saffron silk with heavy gold zari border. The traditional Mysore Dasara procession saree.",
    inStock: true, stockCount: 4, image: getImage(0),
    weight: "760g", zariType: "Heavy Gold Zari", occasion: "Dasara, Festivals",
  },
  {
    id: "s77", name: "Gold Zari Navy Grand", price: 47000,
    category: "Premium Gold Zari Silk", color: "Navy Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "Navy blue with grand gold zari border. Classic combination worn at Karnataka state ceremonies.",
    inStock: true, stockCount: 3, image: getImage(1),
    weight: "810g", zariType: "22K Gold Zari", occasion: "State Events, Weddings",
  },
  {
    id: "s78", name: "Silver Zari Heritage White", price: 41000,
    category: "Premium Gold Zari Silk", color: "Pure White", fabric: "Pure Mulberry Silk",
    artisanId: "a5", artisanName: "Krishnamurthy Iyengar", location: "Srirangapatna, Mandya",
    description: "White silk with heavy pure silver zari. Traditional wear for temple ceremonies and auspicious functions.",
    inStock: true, stockCount: 3, image: getImage(2),
    weight: "820g", zariType: "Pure Silver Zari", occasion: "Temple, Weddings",
  },
  {
    id: "s79", name: "Gold Zari Rose Grandeur", price: 44500,
    category: "Premium Gold Zari Silk", color: "Deep Rose", fabric: "Pure Mulberry Silk",
    artisanId: "a3", artisanName: "Venkatesh Shastri", location: "Hunsur, Mysore",
    description: "Deep rose with heavy gold zari. The floral theme in the zari matches the petal-like color.",
    inStock: true, stockCount: 2, image: getImage(3),
    weight: "790g", zariType: "22K Gold Zari", occasion: "Grand Occasions",
  },
  {
    id: "s80", name: "Gold Zari Silk Dupion", price: 36000,
    category: "Premium Gold Zari Silk", color: "Dupion Gold", fabric: "Dupion Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Unique dupion silk with raw texture and pure gold zari. Rare, textured, and unmistakably premium.",
    inStock: true, stockCount: 5, image: getImage(4), badge: "Unique Texture",
    weight: "750g", zariType: "Gold Zari", occasion: "Formal Events, Weddings",
  },

  // Designer Collection (81-100)
  {
    id: "s81", name: "Contemporary Mysore Fusion", price: 22000,
    category: "Designer Collection", color: "Midnight Blue & Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "A bold fusion of traditional Mysore weaving with contemporary geometric art. Exhibited in Delhi Design Week.",
    inStock: true, stockCount: 6, image: getImage(5), badge: "Award Winning",
    weight: "520g", zariType: "Designer Zari", occasion: "Fashion Events, Parties",
  },
  {
    id: "s82", name: "Ombre Silk Mysore", price: 24500, originalPrice: 29000,
    category: "Designer Collection", color: "Ombre Blue to Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Groundbreaking ombre effect saree transitioning from deep blue to gold. Only artisan in India mastering this.",
    inStock: true, stockCount: 4, image: getImage(6), badge: "Unique in India",
    weight: "490g", zariType: "Gradient Zari", occasion: "Fashion, Weddings",
  },
  {
    id: "s83", name: "Art Deco Silk", price: 26000,
    category: "Designer Collection", color: "Black & Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Art Deco inspired Mysore silk with geometric gold zari patterns. Exhibited internationally.",
    inStock: true, stockCount: 3, image: getImage(7), badge: "International",
    weight: "510g", zariType: "Geometric Gold Zari", occasion: "Fashion, Events",
  },
  {
    id: "s84", name: "Nature Bloom Silk", price: 19800,
    category: "Designer Collection", color: "Garden Green", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Nature-inspired design with floral and leaf motifs woven in gold. Fresh, artistic, and contemporary.",
    inStock: true, stockCount: 7, image: getImage(8),
    weight: "480g", zariType: "Floral Gold Zari", occasion: "Garden Parties, Casual",
  },
  {
    id: "s85", name: "Abstract Mysore Art", price: 28000,
    category: "Designer Collection", color: "Multicolor", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Abstract expressionist patterns using natural dyes. Each piece is unique — no two are identical.",
    inStock: true, stockCount: 2, image: getImage(9), badge: "One of a Kind",
    weight: "500g", zariType: "Mixed Zari", occasion: "Art Events, Fashion",
  },
  {
    id: "s86", name: "Constellation Silk", price: 25000,
    category: "Designer Collection", color: "Midnight Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Night sky inspired silk with gold zari stars and constellation patterns. Otherworldly beauty.",
    inStock: true, stockCount: 4, image: getImage(10),
    weight: "495g", zariType: "Star Pattern Zari", occasion: "Evening Events",
  },
  {
    id: "s87", name: "Vintage Kantha Mysore", price: 21000,
    category: "Designer Collection", color: "Antique Rose", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Mysore silk meets vintage Kantha embroidery tradition. A Bengal-Karnataka collaboration.",
    inStock: true, stockCount: 5, image: getImage(11),
    weight: "505g", zariType: "Kantha Thread", occasion: "Cultural Events, Parties",
  },
  {
    id: "s88", name: "Architectural Silk", price: 27000,
    category: "Designer Collection", color: "Stone White", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Inspired by Mysore palace architecture — arches, jalis, and mosaics recreated in zari.",
    inStock: true, stockCount: 3, image: getImage(12), badge: "Architect's Pick",
    weight: "515g", zariType: "Architecture Zari", occasion: "Grand Events, Weddings",
  },
  {
    id: "s89", name: "Pop Art Mysore Silk", price: 18500,
    category: "Designer Collection", color: "Vibrant Multi", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Pop art meets heritage weaving. Bold colors and graphic patterns for the young fashion lover.",
    inStock: true, stockCount: 6, image: getImage(13),
    weight: "475g", zariType: "Colored Thread", occasion: "Fashion, Youth Events",
  },
  {
    id: "s90", name: "Minimal Luxury Silk", price: 23000,
    category: "Designer Collection", color: "Warm Beige", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Less is more — a single gold line border on the purest beige silk. For the connoisseur of simplicity.",
    inStock: true, stockCount: 8, image: getImage(14), badge: "Minimalist",
    weight: "465g", zariType: "Single Gold Line", occasion: "Formal, Office Premium",
  },
  {
    id: "s91", name: "Watercolor Woven Silk", price: 29000, originalPrice: 35000,
    category: "Designer Collection", color: "Watercolor Pastels", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Watercolor painting technique applied to silk dyeing before weaving. Truly one-of-a-kind artistic piece.",
    inStock: true, stockCount: 2, image: getImage(0), badge: "Artisan Limited",
    weight: "488g", zariType: "Minimal Gold Thread", occasion: "Art Exhibitions, Parties",
  },
  {
    id: "s92", name: "Vintage Rose Gold", price: 20500,
    category: "Designer Collection", color: "Rose Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Rose gold tones with modern geometric zari. A bridge between tradition and modern luxury fashion.",
    inStock: true, stockCount: 5, image: getImage(1),
    weight: "485g", zariType: "Rose Gold Zari", occasion: "Parties, Weddings",
  },
  {
    id: "s93", name: "Celestial Blue Designer", price: 24000,
    category: "Designer Collection", color: "Celestial Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Celestial blue with silver and gold combined zari depicting moon phases. Mystical and beautiful.",
    inStock: true, stockCount: 4, image: getImage(2),
    weight: "492g", zariType: "Moon Silver-Gold Zari", occasion: "Evening Events",
  },
  {
    id: "s94", name: "Heritage Meets Modern", price: 26500,
    category: "Designer Collection", color: "Deep Burgundy", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Traditional Mysore motifs reimagined with contemporary color theory. Burgundy with gold accents.",
    inStock: true, stockCount: 3, image: getImage(3),
    weight: "500g", zariType: "Contemporary Gold Zari", occasion: "Premium Events",
  },
  {
    id: "s95", name: "Emerald Designer Silk", price: 22500,
    category: "Designer Collection", color: "Emerald", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Gem-toned emerald silk with gold zari inspired by Mughal jewelry motifs. Precious and rare.",
    inStock: true, stockCount: 5, image: getImage(4),
    weight: "498g", zariType: "Jewel Motif Zari", occasion: "Formal, Weddings",
  },
  {
    id: "s96", name: "Silk Fusion Mandala", price: 30000, originalPrice: 36000,
    category: "Designer Collection", color: "Terracotta & Gold", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Mandala patterns woven throughout the entire silk body. Meditative artistry meets luxury fashion.",
    inStock: true, stockCount: 2, image: getImage(5), badge: "Fusion Art",
    weight: "510g", zariType: "Mandala Gold Zari", occasion: "Cultural, Premium Events",
  },
  {
    id: "s97", name: "Earthy Ochre Designer", price: 19200,
    category: "Designer Collection", color: "Ochre Yellow", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Rich ochre silk with earthy tones and modern minimalist gold border. Inspired by Hampi's ancient walls.",
    inStock: true, stockCount: 7, image: getImage(6),
    weight: "480g", zariType: "Minimal Gold Line", occasion: "Cultural Events, Casual",
  },
  {
    id: "s98", name: "Neo Heritage Silk", price: 27500,
    category: "Designer Collection", color: "Charcoal Blue", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Charcoal silk with revolutionary neo-heritage zari patterns combining Mysore and modern design.",
    inStock: true, stockCount: 4, image: getImage(7), badge: "Neo Heritage",
    weight: "505g", zariType: "Neo Heritage Zari", occasion: "Fashion Weeks, Events",
  },
  {
    id: "s99", name: "Biophilic Silk Design", price: 23500,
    category: "Designer Collection", color: "Forest Multi-tone", fabric: "Pure Mulberry Silk",
    artisanId: "a6", artisanName: "Annapoorna Devi", location: "Mandya",
    description: "Nature-inspired forest motifs with organic dyes and gold thread. Sustainable luxury saree.",
    inStock: true, stockCount: 6, image: getImage(8),
    weight: "490g", zariType: "Organic Gold Thread", occasion: "Eco Events, Casual",
  },
  {
    id: "s100", name: "Grand Legacy Silk", price: 75000, originalPrice: 90000,
    category: "Designer Collection", color: "Royal Tricolor", fabric: "Pure Mulberry Silk",
    artisanId: "a1", artisanName: "Ramaiah Devaraju", location: "Arsikere, Hassan",
    description: "The ultimate collectible. Collaboration between master artisan Ramaiah and designer Annapoorna. 35-day weave. Investment grade.",
    inStock: true, stockCount: 1, image: getImage(9), badge: "Investment Piece",
    weight: "980g", zariType: "22K + 24K Combined Gold Zari", occasion: "Collections, Museums, Grand Weddings",
    careInstructions: "Professional conservation care only",
  },
];



module.exports = { sarees, artisans, categories };
